zone_entries:
  - name: "demo.lan"
    file: "demo.lan.db"
    records:
      - name: "@"
        type: "SOA"
        value: "dealer.demo.lan. root.demo.lan. (2001062501 21600 3600 604800 86400)"
      - name: "@"
        type: "NS"
        value: "dealer.demo.lan."
      - name: "dealer"
        type: "A"
        value: "192.168.122.10"
      - name: "nadm"
        type: "A"
        value: "192.168.122.20"
      - name: "web-01"
        type: "A"
        value: "192.168.122.150"
      - name: "web-02"
        type: "A"
        value: "192.168.122.250"
      - name: "web"
        type: "A"
        value: "192.168.122.150"
      - name: "web"
        type: "A"
        value: "192.168.122.250"
  - name: "122.168.192.in-addr.arpa"
    file: "192.168.122.db"
    records:
      - name: "@"
        type: "SOA"
        value: "dealer.demo.lan. root.demo.lan. (2001062501 21600 3600 604800 86400)"
      - name: "@"
        type: "NS"
        value: "dealer.demo.lan."
      - name: "10"
        type: "PTR"
        value: "dealer.demo.lan."
      - name: "150"
        type: "PTR"
        value: "web-01.demo.lan."
      - name: "250"
        type: "PTR"
        value: "web-02.demo.lan."
      - name: "20"
        type: "PTR"
        value: "nadm.demo.lan"
